import React, { useState, useEffect } from 'react'
import {
  Sparkles, FileDown, Clock, MapPin,
  Utensils, Compass, BedDouble, Calendar, AlertCircle,
  RefreshCw, Printer, Copy, Check,
  DollarSign, ShieldCheck, Zap
} from 'lucide-react'

// Document generator helpers for Microsoft Word (.doc)
function exportToWordDocument(plan, destination, travellers, travelParty, budgetAmount, flight, hotel) {
  const htmlContent = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${plan.tripTitle || 'Trip Itinerary'}</title>
      <style>
        body { font-family: 'Calibri', 'Arial', sans-serif; line-height: 1.6; color: #2C241E; padding: 30px; background-color: #FAF7F2; }
        h1 { color: #E06D53; font-size: 24pt; border-bottom: 2px solid #E06D53; padding-bottom: 8px; margin-bottom: 5px; }
        h2 { color: #3E7B6C; font-size: 16pt; margin-top: 20px; border-bottom: 1px solid #E6DFD5; padding-bottom: 4px; }
        h3 { color: #2C241E; font-size: 13pt; margin-top: 15px; }
        .summary-box { background-color: #FAF7F2; border-left: 4px solid #E06D53; padding: 15px; margin: 15px 0; }
        .meta-table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        .meta-table td { padding: 8px 12px; border: 1px solid #E6DFD5; font-size: 10.5pt; color: #2C241E; }
        .meta-table th { background-color: #F3EFE6; padding: 8px 12px; border: 1px solid #E6DFD5; text-align: left; color: #2C241E; }
        .day-header { background-color: #E06D53; color: white; padding: 8px 12px; font-weight: bold; font-size: 12pt; margin-top: 20px; border-radius: 4px; }
        .slot-card { margin: 10px 0; padding: 10px; background-color: #FFFFFF; border-left: 3px solid #E06D53; border: 1px solid #E6DFD5; }
        .time-badge { font-weight: bold; color: #E06D53; font-size: 10pt; }
        .rating-badge { color: #d97706; font-weight: bold; }
        .tips-list { background-color: #fffbeb; border: 1px solid #fde68a; padding: 12px 20px; border-radius: 4px; }
        .footer { font-size: 9pt; color: #64748b; margin-top: 30px; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
      </style>
    </head>
    <body>
      <h1>${plan.tripTitle || `${destination?.city || 'Destination'} Travel Itinerary`}</h1>
      <p><em>Generated by PlanTrip AI Agent · Real Google Review Verified Data</em></p>

      <div class="summary-box">
        <strong>Trip Overview:</strong> ${plan.summary}<br><br>
        <strong>Travel Party:</strong> ${plan.partyType || 'Custom Group'} (${travellers} Travellers) · <strong>Estimated Cost:</strong> ${plan.totalEstimatedCost}
      </div>

      <h2>Itemized Estimated Budget Breakdown</h2>
      <table class="meta-table">
        <tr><th>Expense Category</th><th>Estimated Total</th></tr>
        <tr><td><strong>Flights & Airfare</strong></td><td>${plan.costBreakdown?.flights || 'RM 720'}</td></tr>
        <tr><td><strong>Hotel & Accommodation</strong></td><td>${plan.costBreakdown?.accommodation || 'RM 1,120'}</td></tr>
        <tr><td><strong>Dining & Gastronomy</strong></td><td>${plan.costBreakdown?.foodAndDining || 'RM 900'}</td></tr>
        <tr><td><strong>Attractions & Activities</strong></td><td>${plan.costBreakdown?.attractionsAndActivities || 'RM 540'}</td></tr>
        <tr><td><strong>Local Transport & Transfers</strong></td><td>${plan.costBreakdown?.localTransport || 'RM 300'}</td></tr>
        <tr><td><strong>Total Estimated Investment</strong></td><td><strong>${plan.totalEstimatedCost}</strong></td></tr>
      </table>

      <h2>Travel Logistics & Reservations</h2>
      <table class="meta-table">
        <tr>
          <th>Category</th>
          <th>Details & Confirmation</th>
          <th>Provider</th>
        </tr>
        <tr>
          <td><strong>Flight</strong></td>
          <td>${flight ? `${flight.airline} (${flight.depart} → ${flight.arrive}) · RM ${flight.totalPrice}` : 'Booked independently'}</td>
          <td>${flight ? flight.provider : 'Direct'}</td>
        </tr>
        <tr>
          <td><strong>Accommodation</strong></td>
          <td>${hotel ? `${hotel.name} (${hotel.area}) · RM ${hotel.price || hotel.totalPrice}` : 'Booked independently'}</td>
          <td>${hotel ? hotel.provider : 'Booking.com'}</td>
        </tr>
        <tr>
          <td><strong>Weather Advice</strong></td>
          <td colspan="2">${plan.weatherAdvice || 'Mild temperatures, pack light comfortable walking clothes.'}</td>
        </tr>
      </table>

      <h2>Detailed Day-by-Day Schedule</h2>
      ${plan.days?.map(day => `
        <div class="day-header">DAY ${day.dayNumber} · ${day.theme} (${day.date})</div>

        <div class="slot-card">
          <span class="time-badge">MORNING (${day.morning?.time || '09:00 - 12:00'})</span><br>
          <strong>${day.morning?.title}</strong> <span class="rating-badge">${day.morning?.rating || ''}</span><br>
          <small>📍 ${day.morning?.location || ''}</small><br>
          ${day.morning?.description || ''}
        </div>

        <div class="slot-card" style="border-left-color: #f59e0b;">
          <span class="time-badge" style="color: #b45309;">LUNCH (${day.lunch?.time || '12:30 - 14:00'})</span><br>
          <strong>🍽️ ${day.lunch?.name}</strong> (${day.lunch?.cuisine} · Price: ${day.lunch?.priceTier})<br>
          <em>Must Try:</em> ${day.lunch?.mustTry || 'Chef signature specialty'}
        </div>

        <div class="slot-card">
          <span class="time-badge">AFTERNOON (${day.afternoon?.time || '14:30 - 17:30'})</span><br>
          <strong>${day.afternoon?.title}</strong> <span class="rating-badge">${day.afternoon?.rating || ''}</span><br>
          <small>📍 ${day.afternoon?.location || ''}</small><br>
          ${day.afternoon?.description || ''}
        </div>

        <div class="slot-card" style="border-left-color: #f59e0b;">
          <span class="time-badge" style="color: #b45309;">DINNER (${day.dinner?.time || '18:30 - 20:30'})</span><br>
          <strong>🍷 ${day.dinner?.name}</strong> (${day.dinner?.cuisine} · Price: ${day.dinner?.priceTier})<br>
          <em>Specialty:</em> ${day.dinner?.mustTry || 'Signature tasting dinner'}
        </div>

        <div class="slot-card" style="border-left-color: #8b5cf6;">
          <span class="time-badge" style="color: #6d28d9;">EVENING (${day.evening?.time || '21:00 - 22:30'})</span><br>
          <strong>${day.evening?.title}</strong><br>
          ${day.evening?.description || ''}
        </div>

        <p><small><strong>Daily Budget Estimate:</strong> ${day.dailyBudgetEstimate} · <strong>Transit Note:</strong> ${day.transportNote}</small></p>
      `).join('')}

      <h2>Essential Packing List & Tips</h2>
      <div class="tips-list">
        <ul>
          ${plan.packingList?.map(item => `<li>${item}</li>`).join('') || ''}
        </ul>
      </div>

      <div class="footer">
        Generated by PlanTrip AI · Safe travels & unforgettable memories!
      </div>
    </body>
    </html>
  `

  const blob = new Blob(['\ufeff' + htmlContent], {
    type: 'application/msword'
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${destination?.city || 'Trip'}_Itinerary_${plan.partyType?.replace(/\s+/g, '_') || 'Travel'}.doc`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export default function AIAgentPage({
  destination,
  basket = [],
  selectedFlight = null,
  selectedHotel = null,
  departureDate = '2026-09-15',
  returnDate = '2026-09-19',
  durationDays = 4,
  travellers = 2,
  travelParty = 'couple',
  budgetTier = 'balanced',
  budgetAmount = 3500,
  travelPace = 'moderate',
  onNavigateToExplore,
  onNavigateToCompare
}) {
  const [itineraryPlan, setItineraryPlan] = useState(null)
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)
  const [lastUpdatedNotice, setLastUpdatedNotice] = useState('')

  const attractions = basket.filter(i => i.type === 'attraction' || i.category)
  const restaurants = basket.filter(i => i.type === 'restaurant' || i.cuisine)

  // Trigger Plan Generation
  const generatePlan = async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/ai/plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          destination,
          durationDays,
          departureDate,
          returnDate,
          travellers,
          travelParty,
          budgetTier,
          budgetAmount,
          travelPace,
          attractions,
          restaurants,
          flight: selectedFlight,
          hotel: selectedHotel
        })
      })
      const data = await res.json()
      if (data.plan) {
        setItineraryPlan(data.plan)
      }
    } catch (_err) {
      // Handled cleanly
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    generatePlan()
  }, [destination, durationDays, travelParty, budgetTier, budgetAmount, travelPace])

  const copyAsMarkdown = () => {
    if (!itineraryPlan) return
    const md = `# ${itineraryPlan.tripTitle}\n\n${itineraryPlan.summary}\n\n**Total Budget:** ${itineraryPlan.totalEstimatedCost}\n\n` +
      itineraryPlan.days?.map(d => `## Day ${d.dayNumber}: ${d.theme} (${d.date})\n- **Morning:** ${d.morning?.title} (${d.morning?.time})\n- **Lunch:** ${d.lunch?.name} (${d.lunch?.cuisine})\n- **Afternoon:** ${d.afternoon?.title} (${d.afternoon?.time})\n- **Dinner:** ${d.dinner?.name} (${d.dinner?.cuisine})\n- **Evening:** ${d.evening?.title}\n- *Budget:* ${d.dailyBudgetEstimate}\n`).join('\n')

    navigator.clipboard.writeText(md)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="ai-agent-page">
      {/* Page Header */}
      <div className="ai-header">
        <div className="container">
          <div className="ai-title-row">
            <div>
              <h1 className="page-title">
                Your Tailored {destination?.city || 'Trip'} Itinerary
              </h1>
              <p className="page-subtitle">
                Optimized for <strong>{travellers} Travelers ({travelParty})</strong> · Target Budget <strong>RM {budgetAmount.toLocaleString()}</strong> · Synthesizing {attractions.length} chosen sights and {restaurants.length} dining spots into a time-clustered schedule.
              </p>
            </div>

            {/* Document Export Buttons */}
            {itineraryPlan && (
              <div className="export-btn-group">
                <button
                  className="btn-download-doc"
                  onClick={() => exportToWordDocument(itineraryPlan, destination, travellers, travelParty, budgetAmount, selectedFlight, selectedHotel)}
                >
                  <FileDown size={18} />
                  <span>Download Word Document (.doc)</span>
                </button>

                <button
                  className="btn-print-doc"
                  onClick={() => window.print()}
                  title="Print or Save as PDF"
                >
                  <Printer size={18} />
                  <span>PDF / Print</span>
                </button>

                <button
                  className="btn-copy-md"
                  onClick={copyAsMarkdown}
                  title="Copy as Markdown text"
                >
                  {copied ? <Check size={18} /> : <Copy size={18} />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
            )}
          </div>

        </div>
      </div>

      <div className="container ai-main-grid single-column-preview">
        {/* ITINERARY DOCUMENT PREVIEW */}
        <div className="itinerary-preview-col full-width-preview">
          {loading ? (
            <div className="ai-generating-card">
              <div className="ai-orb-pulse">
                <Sparkles size={40} />
              </div>
              <h3>Preparing your itinerary...</h3>
              <p>
                Building your day-by-day plan for {travelParty} travelers with a total budget of RM {budgetAmount.toLocaleString()}.
              </p>
            </div>
          ) : itineraryPlan ? (
            <div className="document-sheet">
              {lastUpdatedNotice && (
                <div className="ai-refine-success-banner">
                  <Sparkles size={16} className="sparkle-spin" />
                  <span>{lastUpdatedNotice}</span>
                </div>
              )}

              {/* Document Header */}
              <div className="doc-header">
                <div className="doc-kicker-row">
                  <div className="doc-kicker">OFFICIAL TRIP ITINERARY</div>
                  {itineraryPlan.aiRefined && (
                    <span className="doc-live-sync-badge">
                      <Sparkles size={12} /> Live AI Refined & Synced
                    </span>
                  )}
                </div>
                <h2 className="doc-title">{itineraryPlan.tripTitle}</h2>
                <p className="doc-summary">{itineraryPlan.summary}</p>

                <div className="doc-meta-grid">
                  <div className="doc-meta-item">
                    <Calendar size={16} />
                    <div>
                      <small>DATES & PARTY</small>
                      <strong>{departureDate} — {returnDate} ({durationDays} Days · {travellers} Pax)</strong>
                    </div>
                  </div>

                  <div className="doc-meta-item">
                    <DollarSign size={16} />
                    <div>
                      <small>ESTIMATED TOTAL</small>
                      <strong>{itineraryPlan.totalEstimatedCost}</strong>
                    </div>
                  </div>

                  <div className="doc-meta-item">
                    <BedDouble size={16} />
                    <div>
                      <small>ACCOMMODATION</small>
                      <strong>{selectedHotel ? `${selectedHotel.name}` : `${destination?.city || 'Central'} Stay`}</strong>
                    </div>
                  </div>
                </div>

                {/* ITEMISED BUDGET BREAKDOWN */}
                {itineraryPlan.costBreakdown && (
                  <div className="budget-breakdown-card">
                    <h4>
                      <DollarSign size={15} /> Itemized Budget Breakdown
                    </h4>
                    <div className="breakdown-grid">
                      <div className="breakdown-item">
                        <span>Flights & Airfare</span>
                        <strong>{itineraryPlan.costBreakdown.flights}</strong>
                      </div>
                      <div className="breakdown-item">
                        <span>Stays & Hotel</span>
                        <strong>{itineraryPlan.costBreakdown.accommodation}</strong>
                      </div>
                      <div className="breakdown-item">
                        <span>Food & Dining</span>
                        <strong>{itineraryPlan.costBreakdown.foodAndDining}</strong>
                      </div>
                      <div className="breakdown-item">
                        <span>Attractions & Sights</span>
                        <strong>{itineraryPlan.costBreakdown.attractionsAndActivities}</strong>
                      </div>
                      <div className="breakdown-item">
                        <span>Local Transport</span>
                        <strong>{itineraryPlan.costBreakdown.localTransport}</strong>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Day-by-Day Timetable */}
              <div className="doc-days-list">
                {itineraryPlan.days?.map(day => (
                  <div key={day.dayNumber} className={`day-block ${day.aiRefined ? 'ai-refined-day' : ''}`}>
                    <div className="day-title-bar">
                      <span className="day-num-tag">DAY {day.dayNumber}</span>
                      <strong className="day-theme">{day.theme}</strong>
                      {day.aiRefined && (
                        <span className="day-refined-pill">
                          <Zap size={11} /> AI Refined
                        </span>
                      )}
                      <span className="day-date-tag">{day.date}</span>
                    </div>

                    <div className="day-slots-grid">
                      {/* Morning */}
                      <div className={`slot-item morning-slot ${day.morning?.aiRefined ? 'ai-refined-slot' : ''}`}>
                        <div className="slot-time-row">
                          <div className="slot-time"><Clock size={13} /> {day.morning?.time}</div>
                          {day.morning?.aiRefined && <span className="slot-ai-refined-tag"><Sparkles size={10} /> AI Refined</span>}
                        </div>
                        <div className="slot-heading">
                          <Compass size={14} className="slot-icon" />
                          <strong>{day.morning?.title}</strong>
                          <span className="rating-pill">{day.morning?.rating}</span>
                        </div>
                        <p className="slot-description">{day.morning?.description}</p>
                        <small className="slot-location"><MapPin size={12} /> {day.morning?.location}</small>
                      </div>

                      {/* Lunch */}
                      <div className={`slot-item dining-slot ${day.lunch?.aiRefined ? 'ai-refined-slot' : ''}`}>
                        <div className="slot-time-row">
                          <div className="slot-time"><Clock size={13} /> {day.lunch?.time}</div>
                          {day.lunch?.aiRefined && <span className="slot-ai-refined-tag"><Sparkles size={10} /> AI Refined</span>}
                        </div>
                        <div className="slot-heading">
                          <Utensils size={14} className="slot-icon dining" />
                          <strong>{day.lunch?.name}</strong>
                          <span className="tier-pill">{day.lunch?.priceTier}</span>
                        </div>
                        <div className="cuisine-line">{day.lunch?.cuisine}</div>
                        <small className="must-try"><strong>Must Try:</strong> {day.lunch?.mustTry}</small>
                      </div>

                      {/* Afternoon */}
                      <div className={`slot-item afternoon-slot ${day.afternoon?.aiRefined ? 'ai-refined-slot' : ''}`}>
                        <div className="slot-time-row">
                          <div className="slot-time"><Clock size={13} /> {day.afternoon?.time}</div>
                          {day.afternoon?.aiRefined && <span className="slot-ai-refined-tag"><Sparkles size={10} /> AI Refined</span>}
                        </div>
                        <div className="slot-heading">
                          <Compass size={14} className="slot-icon" />
                          <strong>{day.afternoon?.title}</strong>
                          <span className="rating-pill">{day.afternoon?.rating}</span>
                        </div>
                        <p className="slot-description">{day.afternoon?.description}</p>
                        <small className="slot-location"><MapPin size={12} /> {day.afternoon?.location}</small>
                      </div>

                      {/* Dinner */}
                      <div className={`slot-item dining-slot ${day.dinner?.aiRefined ? 'ai-refined-slot' : ''}`}>
                        <div className="slot-time-row">
                          <div className="slot-time"><Clock size={13} /> {day.dinner?.time}</div>
                          {day.dinner?.aiRefined && <span className="slot-ai-refined-tag"><Sparkles size={10} /> AI Refined</span>}
                        </div>
                        <div className="slot-heading">
                          <Utensils size={14} className="slot-icon dining" />
                          <strong>{day.dinner?.name}</strong>
                          <span className="tier-pill">{day.dinner?.priceTier}</span>
                        </div>
                        <div className="cuisine-line">{day.dinner?.cuisine}</div>
                        <small className="must-try"><strong>Must Try:</strong> {day.dinner?.mustTry}</small>
                      </div>

                      {/* Evening */}
                      <div className={`slot-item evening-slot ${day.evening?.aiRefined ? 'ai-refined-slot' : ''}`}>
                        <div className="slot-time-row">
                          <div className="slot-time"><Clock size={13} /> {day.evening?.time}</div>
                          {day.evening?.aiRefined && <span className="slot-ai-refined-tag"><Sparkles size={10} /> AI Refined</span>}
                        </div>
                        <div className="slot-heading">
                          <Sparkles size={14} className="slot-icon evening" />
                          <strong>{day.evening?.title}</strong>
                        </div>
                        <p className="slot-description">{day.evening?.description}</p>
                      </div>
                    </div>

                    <div className="day-footer-meta">
                      <span className="budget-tag">{day.dailyBudgetEstimate}</span>
                      <span className="transit-tag">{day.transportNote}</span>
                    </div>
                  </div>
                ))}
              </div>

              {/* Party Tips & Packing List */}
              <div className="doc-tips-section">
                {itineraryPlan.partyTips && (
                  <div className="tips-card">
                    <h4>
                      <ShieldCheck size={16} /> Tips for {itineraryPlan.partyType || 'Your Group'}
                    </h4>
                    <ul>
                      {itineraryPlan.partyTips.map((tip, idx) => (
                        <li key={idx}>{tip}</li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="tips-card">
                  <h4>
                    <Sparkles size={16} /> Essential Packing Checklist
                  </h4>
                  <ul>
                    {itineraryPlan.packingList?.map((item, idx) => (
                      <li key={idx}>{item}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          ) : (
            <div className="error-card">
              <AlertCircle size={32} />
              <h3>Failed to generate itinerary</h3>
              <p>Please check your connection and try regenerating.</p>
              <button className="btn-retry" onClick={generatePlan}>
                <RefreshCw size={16} /> Retry
              </button>
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
